# Values taken from the real-world cardiovascular-disease-dataset: https://www.kaggle.com/datasets/sulianova/cardiovascular-disease-dataset 
# Reading in the data set and calculating the required statistics from it:

import pandas as pd
# The delimiter parameter to remove colons:
dataset = pd.read_csv("cardio_train.csv", delimiter=';')
cardio_dataframe = pd.DataFrame(dataset)
print(cardio_dataframe.head())
print(cardio_dataframe['gender'].std())
print(cardio_dataframe['gender'].mean())
print(cardio_dataframe['gender'].count())
print("\n Ages info")
print(cardio_dataframe['age'].std())
print(cardio_dataframe['age'].mean())
print("\nHeight info:")
print(cardio_dataframe['height'].std())
print(cardio_dataframe['height'].mean())
print("\nWeight info:")
print(cardio_dataframe['weight'].std())
print(cardio_dataframe['weight'].mean())
print("diastolic info:")
print(cardio_dataframe['ap_lo'].std())
print(cardio_dataframe['ap_lo'].mean())
print("Systolic info:")
print(cardio_dataframe['ap_hi'].std())
print(cardio_dataframe['ap_hi'].mean())
print(cardio_dataframe['cholesterol'].std())
print(cardio_dataframe['cholesterol'].mean())
print(cardio_dataframe['gluc'].std())
print(cardio_dataframe['gluc'].mean())
print("Alcohol info:")
print(cardio_dataframe['alco'].std())
print(cardio_dataframe['alco'].mean())
print("Smoking info:")
print(cardio_dataframe['smoke'].std())
print(cardio_dataframe['smoke'].mean())
print(cardio_dataframe['active'].std())
print(cardio_dataframe['active'].mean())
print(cardio_dataframe['cardio'].std())
print(cardio_dataframe['cardio'].mean())
